services:
  scpi-invest-batch-db:
    image: postgres:16
    container_name: scpiinvestbatch-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

