spring:
  application:
    version: 1.0.0
    name: scpi-invest-plus-batch
  datasource:
    url: jdbc:postgresql://scpi-invest-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://admin:admin@scpi-invest-partner-db:27017/scpi-invest-partner-db?authSource=admin

  elasticsearch:
    hostname: ${ELASTICSEARCH_HOSTNAME}
    port: 9200
    connection-timeout: 1000
    read-timeout: 3000

  s3:
    bucket:
      name: scpi-batch
    file:
      key: scpi-data/scpi.csv

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true