spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    batch:
      jdbc-url: jdbc:postgresql://localhost:5432/batch-db
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
    app:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
