server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
  elasticsearch:
    rest:
      uris: http://localhost:9200
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/mongo_db_app?authSource=admin