spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/mongo_db_app?authSource=admin

  elasticsearch:
    rest:
      uris: http://localhost:9200
    connection-timeout: 1000
    read-timeout: 3000
