apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-scpi-job
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: import-scpi-job
              image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "{{.Values.application.environment }}"
                - name: ELASTICSEARCH_HOSTNAME
                  value: "{{ .Values.elasticsearch.hostname }}"
          restartPolicy: OnFailure