apiVersion: v1
kind: ServiceAccount
metadata:
  name: import-scpi-sa
  namespace: scpi-invest-plus-int
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::205493924920:role/AmazonEKSBatchIRSAImportScpiRoleINT
